# Generated by Django 5.1.7 on 2025-04-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('url_name',), name='unique_url_name')],
            },
        ),
    ]
