# Generated by Django 5.1.7 on 2025-04-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteConfigurations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaritem',
            name='url_name',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
