# Generated by Django 5.1.7 on 2025-04-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteConfigurations', '0002_alter_navbaritem_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaritem',
            name='url_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='navbaritem',
            constraint=models.UniqueConstraint(fields=('url_name',), name='unique_url_name'),
        ),
    ]
