# Generated by Django 5.1.7 on 2025-04-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteConfigurations', '0003_alter_navbaritem_url_name_navbaritem_unique_url_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbaritem',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='navbaritem',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
